name: ios-build-test

on:
  workflow_call:
    inputs:
      build-environment:
        required: true
        type: string
        description: Top-level label for whats being built/tested.
      sync-tag:
        required: false
        type: string
        default: ""
        description: |
          If this is set, our linter will use this to make sure that every other
          job with the same `sync-tag` is identical.
      test-matrix:
        required: true
        type: string
        description: |
          A JSON description of what configs to run later on.

env:
  GIT_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  BUILD_ENVIRONMENT: ${{ inputs.build-environment }}

jobs:
  filter:
    runs-on: [self-hosted, linux.large]
    outputs:
      test-matrix: ${{ steps.filter.outputs.test-matrix }}
      is-test-matrix-empty: ${{ steps.filter.outputs.is-test-matrix-empty }}
      keep-going: ${{ steps.filter.outputs.keep-going }}
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
        with:
          fetch-depth: 1
          submodules: false

      - name: Select all requested test configurations
        id: filter
        uses: ./.github/actions/filter-test-configs
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-matrix: ${{ inputs.test-matrix }}

  build:
    needs: filter
    # Don't run on forked repos
    if: github.repository_owner == 'pytorch' && needs.filter.outputs.is-test-matrix-empty == 'False'
    strategy:
      matrix: ${{ fromJSON(needs.filter.outputs.test-matrix) }}
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    env:
      IOS_PLATFORM: ${{ matrix.ios_platform }}
      IOS_ARCH: ${{ matrix.ios_arch }}
      BUILD_LITE_INTERPRETER: ${{ matrix.use_lite_interpreter }}
      USE_PYTORCH_METAL: ${{ matrix.use_metal }}
      USE_COREML_DELEGATE: ${{ matrix.use_coreml }}
      CUSTOM_OP_LIST: ${{ matrix.use_custom_op_list }}
    timeout-minutes: 240
    steps:
      # [see note: pytorch repo ref]
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main

      - name: Populate CI build options
        shell: bash
        run: |
          set -ex

          if [ -n "${CUSTOM_OP_LIST:-}" ]; then
            echo "SELECTED_OP_LIST=${GITHUB_WORKSPACE}/ios/TestApp/custom_build/${CUSTOM_OP_LIST}" >> "${GITHUB_ENV}"
          fi

      - name: Install brew dependencies
        uses: nick-fields/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 90
          command: |
            # Install dependencies
            brew install libtool

      - name: Setup miniconda for iOS
        uses: pytorch/test-infra/.github/actions/setup-miniconda@main
        with:
          python-version: "3.9"
          environment-file: .github/requirements/conda-env-iOS
          pip-requirements-file: .github/requirements/pip-requirements-iOS.txt

      - name: Setup Fastlane
        uses: nick-fields/retry@v2.8.2
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 90
          command: |
            set -x
            cd ios/TestApp
            # install fastlane
            sudo gem install bundler && bundle install
            bundle update fastlane

      - name: Build PyTorch Mobile Runtime
        run: |
          # shellcheck disable=SC1091
          export TCLLIBPATH="/usr/local/lib"
          python -VV
          ${CONDA_RUN} scripts/build_ios.sh

      - name: Build TestApp
        if: matrix.ios_platform == 'SIMULATOR'
        timeout-minutes: 15
        run: |
          # run the ruby build script
          if ! [ -x "$(command -v xcodebuild)" ]; then
            echo 'Error: xcodebuild is not installed.'
            exit 1
          fi
          ruby scripts/xcode_build.rb -i build_ios/install -x ios/TestApp/TestApp.xcodeproj -p "${IOS_PLATFORM}"

      - name: Run Simulator Tests
        if: matrix.ios_platform == 'SIMULATOR'
        run: |
          # shellcheck disable=SC1091
          # use the pytorch nightly build to generate models
          ${CONDA_RUN} pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
          # generate models for differnet backends
          cd "${GITHUB_WORKSPACE}/ios/TestApp/benchmark"
          mkdir -p ../models
          if [ "${USE_COREML_DELEGATE}" == 1 ]; then
            ${CONDA_RUN} python coreml_backend.py
          else
            cd "${GITHUB_WORKSPACE}"
            ${CONDA_RUN} python test/mobile/model_test/gen_test_model.py ios-test
          fi
          cd "${GITHUB_WORKSPACE}/ios/TestApp/benchmark"
          if [ "${BUILD_LITE_INTERPRETER}" == 1 ]; then
            echo "Setting up the TestApp for LiteInterpreter"
            ruby setup.rb --lite 1
          else
            echo "Setting up the TestApp for Full JIT"
            ruby setup.rb
          fi
          cd "${GITHUB_WORKSPACE}/ios/TestApp"
          # instruments -s -devices
          if [ "${BUILD_LITE_INTERPRETER}" == 1 ]; then
            if [ "${USE_COREML_DELEGATE}" == 1 ]; then
              bundle exec fastlane scan --only_testing TestAppTests/TestAppTests/testCoreML
            else
              bundle exec fastlane scan --skip_testing TestAppTests/TestAppTests/testCoreML
            fi
          else
            bundle exec fastlane scan --only_testing TestAppTests/TestAppTests/testFullJIT
          fi

      - name: Dump Simulator Tests On a Failure
        if: failure() && inputs.ios-platform == 'SIMULATOR'
        run: |
          echo "Simulator Tests Logs:"
          cat /Users/runner/Library/Logs/scan/*.log
