name: Build iOS binaries

on:
  push:
    branches:
      - nightly
    tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
    paths:
      - .github/workflows/build-ios-binaries.yml
      - .github/workflows/_ios-build-test.yml
  pull_request:
    paths:
      - .github/workflows/build-ios-binaries.yml
      - .github/workflows/_ios-build-test.yml
  # NB: We can use this workflow dispatch to test and build iOS binaries manually
  workflow_dispatch:
    inputs:
      use_lite_interpreter:
        description: "Build iOS binaries with PyTorch lite interpreter support"
        type: string
        default: 1
      use_metal:
        description: "Build iOS binaries with Apple Metal"
        type: string
        default: 1
      use_coreml:
        description: "Build iOS binaries with Apple Core ML"
        type: string
        default: 1
      use_custom_op_list:
        description: "Specify the custom ops list to include in the binaries"
        type: string
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

jobs:
  # TODO: Figure out how to migrate this job to M1 runner
  ios-build-test:
    name: ios-build-test
    if: github.event_name != 'schedule' || github.event.schedule == '45 0,8,16 * * 1-5' || github.event.schedule == '45 4 * * 0,6'
    uses: ./.github/workflows/_ios-build-test.yml
    with:
      build-environment: ios-build-test
      sync-tag: ios-build-test
      test-matrix: |
        { include: [
          { config: "default",
            shard: 1,
            num_shards: 1,
            runner: "macos-12",
            ios_platform: "SIMULATOR",
            ios_arch: "x86_64",
            use_lite_interpreter: ${{ inputs.use_lite_interpreter }},
            use_metal: ${{ inputs.use_metal }},
            use_coreml: ${{ inputs.use_coreml }},
            use_custom_op_list: ${{ inputs.use_custom_op_list }}
          },
          { config: "default",
            shard: 1,
            num_shards: 1,
            runner: "macos-12",
            ios_platform: "OS",
            ios_arch: "arm64",
            use_lite_interpreter: ${{ inputs.use_lite_interpreter }},
            use_metal: ${{ inputs.use_metal }},
            use_coreml: ${{ inputs.use_coreml }},
            use_custom_op_list: ${{ inputs.use_custom_op_list }}
          }
        ]}
